In [3]:
import numpy as np
import pandas as pd

from sklearn.model_selection import KFold, cross_val_score
from sklearn.linear_model import LinearRegression,Ridge
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import OneHotEncoder, StandardScaler, OrdinalEncoder
from sklearn.compose import ColumnTransformer

from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_absolute_error

from sklearn.decomposition import PCA

just to simplfy we removed some columns, their existences is not making much difference to the models performance

In [4]:
df = pd.read_csv('/Users/meetsudra/Documents/GitHub/real-estate/above csvs/gurgaon_properties_post_feature_selection_2.csv').drop(columns=['store room','floor_category','balcony','pooja room','others','study room'])
df.head()

,property_type,sector,price,built_up_area,bedRoom,bathroom,agePossession,servant room,furnishing_type,luxury_category
0,flat,sector 86,0.78,1360.0,2,2,New Property,0,1,Medium
1,flat,sector 103,1.05,1365.0,2,2,Relatively New,0,2,Medium
2,flat,sector 70a,0.97,1339.0,3,3,Relatively New,0,1,Medium
3,flat,sector 69,2.05,1889.0,4,4,Relatively New,0,1,High
4,flat,sector 92,1.83,2104.0,4,3,New Property,1,1,Medium

The goal of this module is to find relationship between X and y. We want to find konse feature price ko kis tarah se affect karte he 

This module will let user understand that what factors will either increase or decrease price and by what percentage so that user can make an educated decision.

So basically will do Inference using linear regression model

In [5]:
# 1 --> unfurnished
# 2 --> semi
# 0 --> furnished

# Numerical = bedRoom, bathroom, built_up_area, servant room
# Ordinal = property_type, sector, agePossession, luxury_category
# OHE = sector, agePossession

In [9]:
# making 3 categories out of 5 to make it easier, altho while developing model with 5 or 3 categories it was revealed that there was not much difference in the r2 scores of both the models 
df['agePossession'] = df['agePossession'].replace(
    {
    'Relatively New' : 'New',
    'Moderately Old':'Old',
    'New Property' : 'New',
    'Old Property' : 'Old',
    'Under Construction' : 'Under Construction'
    }
)

In [10]:
df.head()

,property_type,sector,price,built_up_area,bedRoom,bathroom,agePossession,servant room,furnishing_type,luxury_category
0,flat,sector 86,0.78,1360.0,2,2,New,0,1,Medium
1,flat,sector 103,1.05,1365.0,2,2,New,0,2,Medium
2,flat,sector 70a,0.97,1339.0,3,3,New,0,1,Medium
3,flat,sector 69,2.05,1889.0,4,4,New,0,1,High
4,flat,sector 92,1.83,2104.0,4,3,New,1,1,Medium

In [11]:
df['property_type'] = df['property_type'].replace({'flat':0, 'house':1})

/var/folders/8h/xtp_v7md6bs9195xxzbbf5d80000gn/T/ipykernel_1979/3269943006.py:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df['property_type'] = df['property_type'].replace({'flat':0, 'house':1})

In [12]:
df.head()

,property_type,sector,price,built_up_area,bedRoom,bathroom,agePossession,servant room,furnishing_type,luxury_category
0,0,sector 86,0.78,1360.0,2,2,New,0,1,Medium
1,0,sector 103,1.05,1365.0,2,2,New,0,2,Medium
2,0,sector 70a,0.97,1339.0,3,3,New,0,1,Medium
3,0,sector 69,2.05,1889.0,4,4,New,0,1,High
4,0,sector 92,1.83,2104.0,4,3,New,1,1,Medium

In [13]:
df['luxury_category'] = df['luxury_category'].replace({'High':2, 'Medium':1, 'Low':0})

/var/folders/8h/xtp_v7md6bs9195xxzbbf5d80000gn/T/ipykernel_1979/668286068.py:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df['luxury_category'] = df['luxury_category'].replace({'High':2, 'Medium':1, 'Low':0})

In [14]:
df.head()

,property_type,sector,price,built_up_area,bedRoom,bathroom,agePossession,servant room,furnishing_type,luxury_category
0,0,sector 86,0.78,1360.0,2,2,New,0,1,1
1,0,sector 103,1.05,1365.0,2,2,New,0,2,1
2,0,sector 70a,0.97,1339.0,3,3,New,0,1,1
3,0,sector 69,2.05,1889.0,4,4,New,0,1,2
4,0,sector 92,1.83,2104.0,4,3,New,1,1,1

In [21]:
new_df = pd.get_dummies(df, columns=['sector', 'agePossession'], drop_first=True, dtype=int)

In [22]:
X = new_df.drop(columns=['price'])
y = new_df['price']

In [23]:
y_log = np.log1p(y)

In [24]:
y_log

0       0.576613
1       0.717840
2       0.678034
3       1.115142
4       1.040277
          ...
3673    1.000632
3674    0.688135
3675    0.788457
3676    1.702928
3677    0.727549
Name: price, Length: 3678, dtype: float64

In [27]:
scaler = StandardScaler()

X_scaled = scaler.fit_transform(X)

In [28]:
pd.DataFrame(X_scaled,columns=X.columns)

,property_type,built_up_area,bedRoom,bathroom,servant room,furnishing_type,luxury_category,sector_gwal pahari,sector_manesar,sector_sector 1,...,sector_sector 92,sector_sector 93,sector_sector 95,sector_sector 99,sector_sector 99a,sector_sector 9a,sector_sohna road,sector_sohna road road,agePossession_Old,agePossession_Under Construction
0,-0.50611,-0.408513,-0.871748,-0.868136,-0.740697,-0.421886,0.450791,-0.070129,-0.092196,-0.040423,...,-0.170584,-0.05477,-0.127683,-0.0661,-0.093684,-0.05477,-0.213957,-0.05477,-0.60143,-0.296385
1,-0.50611,-0.404379,-0.871748,-0.868136,-0.740697,1.472736,0.450791,-0.070129,-0.092196,-0.040423,...,-0.170584,-0.05477,-0.127683,-0.0661,-0.093684,-0.05477,-0.213957,-0.05477,-0.60143,-0.296385
2,-0.50611,-0.425878,-0.063304,-0.174608,-0.740697,-0.421886,0.450791,-0.070129,-0.092196,-0.040423,...,-0.170584,-0.05477,-0.127683,-0.0661,-0.093684,-0.05477,-0.213957,-0.05477,-0.60143,-0.296385
3,-0.50611,0.028905,0.745140,0.518921,-0.740697,-0.421886,1.883814,-0.070129,-0.092196,-0.040423,...,-0.170584,-0.05477,-0.127683,-0.0661,-0.093684,-0.05477,-0.213957,-0.05477,-0.60143,-0.296385
4,-0.50611,0.206683,0.745140,-0.174608,1.350080,-0.421886,0.450791,-0.070129,-0.092196,-0.040423,...,5.862200,-0.05477,-0.127683,-0.0661,-0.093684,-0.05477,-0.213957,-0.05477,-0.60143,-0.296385
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3673,-0.50611,-0.210063,-0.063304,-0.174608,1.350080,1.472736,1.883814,-0.070129,-0.092196,-0.040423,...,-0.170584,-0.05477,-0.127683,-0.0661,-0.093684,-0.05477,-0.213957,-0.05477,-0.60143,-0.296385
3674,-0.50611,-0.160450,-0.063304,0.518921,1.350080,-0.421886,-0.982233,-0.070129,-0.092196,-0.040423,...,-0.170584,-0.05477,-0.127683,-0.0661,-0.093684,-0.05477,-0.213957,-0.05477,-0.60143,-0.296385
3675,-0.50611,-0.204275,-0.063304,-0.868136,-0.740697,1.472736,0.450791,-0.070129,-0.092196,-0.040423,...,-0.170584,-0.05477,-0.127683,-0.0661,-0.093684,-0.05477,-0.213957,-0.05477,-0.60143,-0.296385
3676,-0.50611,1.071597,0.745140,0.518921,-0.740697,1.472736,0.450791,-0.070129,-0.092196,-0.040423,...,-0.170584,-0.05477,-0.127683,-0.0661,-0.093684,-0.05477,-0.213957,-0.05477,-0.60143,-0.296385
3677,-0.50611,-0.305980,-0.871748,-0.868136,-0.740697,-0.421886,0.450791,-0.070129,-0.092196,-0.040423,...,-0.170584,-0.05477,-0.127683,-0.0661,-0.093684,-0.05477,-0.213957,-0.05477,-0.60143,-0.296385

In [29]:
kfold = KFold(n_splits=10, shuffle=True, random_state=42)
scores = cross_val_score(LinearRegression(),X_scaled,y_log,cv=kfold,scoring='r2')

In [31]:
scores.mean(), scores.std()

(0.8509716091451042, 0.02433400807654884)

In [32]:
lr = LinearRegression()

In [33]:
lr.fit(X_scaled,y_log)

LinearRegression()

In [35]:
lr.coef_.shape

(121,)

using these coefficients we will understand which feature is affecting how to model

In [42]:
pd.DataFrame(lr.coef_.reshape(1,121),columns=X.columns).stack().reset_index().drop(columns=['level_0']).rename(columns={'level_1':'feature',0:'coef'})

                              feature      coef
0                       property_type  0.119383
1                       built_up_area  0.210049
2                             bedRoom  0.054372
3                            bathroom  0.065531
4                        servant room  0.049441
..                                ...       ...
116                  sector_sector 9a -0.005411
117                 sector_sohna road -0.027913
118            sector_sohna road road -0.009395
119                 agePossession_Old -0.008145
120  agePossession_Under Construction  0.014288

[121 rows x 2 columns]

# Regression Analysis

In [44]:
# importing lib
import statsmodels.api as sm

X_scaled_df = pd.DataFrame(X_scaled, columns=X.columns)
# add a constant to X
X_with_const = sm.add_constant(X_scaled_df)

# Fit the model
model = sm.OLS(y_log, X_with_const).fit()

# obtain summary stats 
print(model.summary())

                            OLS Regression Results
==============================================================================
Dep. Variable:                  price   R-squared:                       0.866
Model:                            OLS   Adj. R-squared:                  0.861
Method:                 Least Squares   F-statistic:                     189.7
Date:                Mon, 21 Jul 2025   Prob (F-statistic):               0.00
Time:                        15:35:50   Log-Likelihood:                 640.25
No. Observations:                3678   AIC:                            -1036.
Df Residuals:                    3556   BIC:                            -278.9
Df Model:                         121
Covariance Type:            nonrobust
=====================================================================================================
                                        coef    std err          t      P>|t|      [0.025      0.975]
-----------------------------------------------------------------------------------------------------
const                                 1.0407      0.003    305.233      0.000       1.034       1.047
property_type                         0.1194      0.005     23.138      0.000       0.109       0.129
built_up_area                         0.2100      0.005     42.404      0.000       0.200       0.220
bedRoom                               0.0544      0.006      8.402      0.000       0.042       0.067
bathroom                              0.0655      0.007      9.766      0.000       0.052       0.079
servant room                          0.0494      0.004     11.174      0.000       0.041       0.058
furnishing_type                       0.0012      0.004      0.321      0.748      -0.006       0.008
luxury_category                       0.0071      0.004      1.835      0.067      -0.000       0.015
sector_gwal pahari                    0.0098      0.006      1.586      0.113      -0.002       0.022
sector_manesar                       -0.0224      0.008     -2.949      0.003      -0.037      -0.007
sector_sector 1                      -0.0050      0.005     -1.112      0.266      -0.014       0.004
sector_sector 102                     0.0273      0.013      2.073      0.038       0.001       0.053
sector_sector 103                    -0.0030      0.009     -0.343      0.731      -0.020       0.014
sector_sector 104                     0.0016      0.011      0.146      0.884      -0.019       0.023
sector_sector 105                    -0.0193      0.006     -2.985      0.003      -0.032      -0.007
sector_sector 106                     0.0005      0.008      0.061      0.951      -0.016       0.017
sector_sector 107                    -0.0127      0.010     -1.282      0.200      -0.032       0.007
sector_sector 108                     0.0166      0.010      1.694      0.090      -0.003       0.036
sector_sector 109                     0.0251      0.012      2.128      0.033       0.002       0.048
sector_sector 10a                     0.0050      0.005      1.031      0.303      -0.005       0.015
sector_sector 11                     -0.0151      0.006     -2.520      0.012      -0.027      -0.003
sector_sector 110                     0.0097      0.007      1.422      0.155      -0.004       0.023
sector_sector 111                     0.0162      0.007      2.445      0.015       0.003       0.029
sector_sector 112                     0.0315      0.007      4.583      0.000       0.018       0.045
sector_sector 113                     0.0317      0.009      3.676      0.000       0.015       0.049
sector_sector 12                     -0.0195      0.008     -2.504      0.012      -0.035      -0.004
sector_sector 13                     -0.0124      0.005     -2.453      0.014      -0.022      -0.002
sector_sector 14                      0.0293      0.007      4.385      0.000       0.016       0.042
sector_sector 15                      0.0032      0.005      0.713      0.476      -0.006       0.012
sector_sector 17                      0.0066      0.005      1.454      0.146      -0.002       0.016
sector_sector 17a                     0.0038      0.004      1.052      0.293      -0.003       0.011
sector_sector 17b                     0.0132      0.004      3.263      0.001       0.005       0.021
sector_sector 2                       0.0069      0.010      0.679      0.497      -0.013       0.027
sector_sector 21                     -0.0093      0.005     -2.054      0.040      -0.018      -0.000
sector_sector 22                      0.0358      0.006      5.603      0.000       0.023       0.048
sector_sector 23                      0.0023      0.006      0.404      0.686      -0.009       0.013
sector_sector 24                      0.0209      0.007      3.193      0.001       0.008       0.034
sector_sector 25                      0.0571      0.008      6.891      0.000       0.041       0.073
sector_sector 26                      0.0728      0.008      8.592      0.000       0.056       0.089
sector_sector 27                      0.0069      0.004      1.809      0.070      -0.001       0.014
sector_sector 28                      0.0420      0.009      4.898      0.000       0.025       0.059
sector_sector 3                      -0.0126      0.007     -1.833      0.067      -0.026       0.001
sector_sector 3 phase 2              -0.0117      0.005     -2.496      0.013      -0.021      -0.003
sector_sector 3 phase 3 extension    -0.0140      0.005     -2.794      0.005      -0.024      -0.004
sector_sector 30                      0.0065      0.004      1.482      0.138      -0.002       0.015
sector_sector 31                      0.0223      0.005      4.326      0.000       0.012       0.032
sector_sector 33                      0.0258      0.011      2.424      0.015       0.005       0.047
sector_sector 36                     -0.0069      0.005     -1.315      0.189      -0.017       0.003
sector_sector 36a                     0.0121      0.006      2.186      0.029       0.001       0.023
sector_sector 37                      0.0031      0.004      0.865      0.387      -0.004       0.010
sector_sector 37c                    -0.0117      0.009     -1.245      0.213      -0.030       0.007
sector_sector 37d                     0.0008      0.010      0.072      0.943      -0.020       0.021
sector_sector 38                      0.0120      0.005      2.318      0.021       0.002       0.022
sector_sector 39                      0.0039      0.005      0.710      0.478      -0.007       0.015
sector_sector 4                      -0.0206      0.009     -2.319      0.020      -0.038      -0.003
sector_sector 40                      0.0076      0.004      1.722      0.085      -0.001       0.016
sector_sector 41                      0.0169      0.005      3.173      0.002       0.006       0.027
sector_sector 43                      0.0614      0.010      6.149      0.000       0.042       0.081
sector_sector 45                      0.0270      0.005      5.552      0.000       0.017       0.037
sector_sector 46                      0.0159      0.005      2.974      0.003       0.005       0.026
sector_sector 47                      0.0131      0.006      2.155      0.031       0.001       0.025
sector_sector 48                      0.0540      0.010      5.560      0.000       0.035       0.073
sector_sector 49                      0.0316      0.009      3.582      0.000       0.014       0.049
sector_sector 5                      -0.0031      0.005     -0.688      0.491      -0.012       0.006
sector_sector 50                      0.0712      0.010      6.990      0.000       0.051       0.091
sector_sector 51                      0.0001      0.005      0.024      0.981      -0.009       0.009
sector_sector 52                      0.0050      0.006      0.872      0.383      -0.006       0.016
sector_sector 53                      0.0473      0.006      8.351      0.000       0.036       0.058
sector_sector 54                      0.0486      0.007      6.767      0.000       0.035       0.063
sector_sector 55                      0.0132      0.005      2.492      0.013       0.003       0.024
sector_sector 56                      0.0125      0.010      1.305      0.192      -0.006       0.031
sector_sector 57                      0.0250      0.007      3.683      0.000       0.012       0.038
sector_sector 58                      0.0235      0.005      5.018      0.000       0.014       0.033
sector_sector 59                      0.0314      0.005      6.511      0.000       0.022       0.041
sector_sector 6                      -0.0156      0.005     -2.943      0.003      -0.026      -0.005
sector_sector 60                      0.0239      0.006      4.106      0.000       0.012       0.035
sector_sector 61                      0.0369      0.008      4.343      0.000       0.020       0.054
sector_sector 62                      0.0428      0.006      7.083      0.000       0.031       0.055
sector_sector 63                      0.0352      0.006      6.062      0.000       0.024       0.047
sector_sector 63a                     0.0254      0.006      4.140      0.000       0.013       0.037
sector_sector 65                      0.0720      0.012      6.063      0.000       0.049       0.095
sector_sector 66                      0.0524      0.008      6.181      0.000       0.036       0.069
sector_sector 67                      0.0415      0.009      4.586      0.000       0.024       0.059
sector_sector 67a                     0.0094      0.007      1.423      0.155      -0.004       0.022
sector_sector 68                      0.0109      0.007      1.470      0.142      -0.004       0.026
sector_sector 69                      0.0179      0.012      1.471      0.142      -0.006       0.042
sector_sector 7                      -0.0074      0.008     -0.928      0.354      -0.023       0.008
sector_sector 70                      0.0052      0.009      0.553      0.580      -0.013       0.023
sector_sector 70a                     0.0170      0.010      1.786      0.074      -0.002       0.036
sector_sector 71                     -0.0029      0.007     -0.407      0.684      -0.017       0.011
sector_sector 72                      0.0300      0.007      4.067      0.000       0.016       0.045
sector_sector 73                     -0.0012      0.004     -0.304      0.761      -0.009       0.007
sector_sector 74                      0.0218      0.006      3.519      0.000       0.010       0.034
sector_sector 76                     -0.0006      0.006     -0.110      0.913      -0.012       0.011
sector_sector 77                      0.0009      0.007      0.117      0.907      -0.014       0.015
sector_sector 78                     -0.0046      0.006     -0.744      0.457      -0.017       0.008
sector_sector 79                      0.0130      0.011      1.150      0.250      -0.009       0.035
sector_sector 8                      -0.0134      0.005     -2.838      0.005      -0.023      -0.004
sector_sector 80                      0.0001      0.004      0.026      0.979      -0.008       0.009
sector_sector 81                      0.0171      0.012      1.437      0.151      -0.006       0.040
sector_sector 82                      0.0007      0.009      0.084      0.933      -0.016       0.017
sector_sector 82a                     0.0114      0.006      1.772      0.076      -0.001       0.024
sector_sector 83                     -0.0002      0.011     -0.017      0.986      -0.021       0.021
sector_sector 84                     -0.0097      0.009     -1.051      0.293      -0.028       0.008
sector_sector 85                      0.0088      0.013      0.678      0.498      -0.017       0.034
sector_sector 86                     -0.0040      0.010     -0.391      0.696      -0.024       0.016
sector_sector 88a                     0.0101      0.007      1.502      0.133      -0.003       0.023
sector_sector 88b                    -0.0001      0.004     -0.029      0.977      -0.008       0.008
sector_sector 89                      0.0034      0.010      0.338      0.735      -0.016       0.023
sector_sector 9                      -0.0133      0.005     -2.435      0.015      -0.024      -0.003
sector_sector 90                     -0.0132      0.012     -1.103      0.270      -0.037       0.010
sector_sector 91                      0.0002      0.006      0.026      0.979      -0.012       0.012
sector_sector 92                     -0.0289      0.013     -2.283      0.022      -0.054      -0.004
sector_sector 93                     -0.0038      0.005     -0.721      0.471      -0.014       0.007
sector_sector 95                     -0.0259      0.010     -2.621      0.009      -0.045      -0.007
sector_sector 99                      0.0029      0.006      0.498      0.618      -0.009       0.015
sector_sector 99a                    -0.0132      0.008     -1.730      0.084      -0.028       0.002
sector_sector 9a                     -0.0054      0.005     -1.021      0.307      -0.016       0.005
sector_sohna road                    -0.0279      0.015     -1.806      0.071      -0.058       0.002
sector_sohna road road               -0.0094      0.005     -1.778      0.075      -0.020       0.001
agePossession_Old                    -0.0081      0.005     -1.669      0.095      -0.018       0.001
agePossession_Under Construction      0.0143      0.004      3.604      0.000       0.007       0.022
==============================================================================
Omnibus:                      545.249   Durbin-Watson:                   2.019
Prob(Omnibus):                  0.000   Jarque-Bera (JB):             5130.393
Skew:                          -0.398   Prob(JB):                         0.00
Kurtosis:                       8.731   Cond. No.                         40.4
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.

Users asks : 
if i increase bedroom from 1 to 2 then price kitna badhega, assuming everything is same?

- x₂ --- y = 0.5 × x₂  (coef_ = 0.5)
* 1  --- 0.5
* 2  --- 1.0
* 3  --- 1.5

But in our process we applied y_log and x_scaled, we directly cant apply above interpretation. These transformation cant be ignored

when we use scaling, recieved coefficients are called standardized Coefficients
To make them unStandardized coefficients

Stan_coef = Unstan_coef * std(X)/std(log(y)) {Here X is any column from the dataframe}

In [45]:
y_log.std()

0.5552365394042419

In [48]:
# std(X) unscaled X 
X['bedRoom'].std()

1.2371118133242973

In [51]:
# Stan_coef - bedRoom (0.0544)
0.0544 * (0.555/1.237)

# this could be Unstan_coef, but y_log needs to be reversed

0.024407437348423603

In [54]:
# this is the real coefficient of bedRoom column
Unstan_coef = np.expm1(0.024407437348423603)
Unstan_coef

# If the price of house with 1 bedRoom is 1 cr then house with 2 bedRoom will be 1.024cr

0.02470773705206254

In [ ]:
# lets do it for built_up_area 

built_up_area_coef = 0.2100 
Unstan_coef = np.expm1((built_up_area_coef * y_log.std())/X['built_up_area'].std())
Unstan_coef

9.640515437065593e-05

In [57]:
Unstan_coef*100

0.009640515437065593